// Auto-generated API types from Swagger/OpenAPI
// Run: npm run generate:api-types
// This file is generated automatically - do not edit manually

// Placeholder - will be generated by openapi-typescript
export type paths = Record<string, unknown>;
export type components = Record<string, unknown>;
